System check identified some issues:

WARNINGS:
?: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anymore and which does have unfixed security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS . You should consider strongly switching to a different editor (maybe CKEditor 5 respectively django-ckeditor-5 after checking whether the CKEditor 5 license terms work for you) or switch to the non-free CKEditor 4 LTS package. See https://ckeditor.com/ckeditor-4-support/ for more on this. (Note! This notice has been added by the django-ckeditor developers and we are not affiliated with CKSource and were not involved in the licensing change, so please refrain from complaining to us. Thanks.)
?: (staticfiles.W004) The directory 'E:\Local Projects\Django web host\media\websites\Resham_fgdfgfg\Admin Potfoilio\static' in the STATICFILES_DIRS setting does not exist.

System check identified 2 issues (0 silenced).
Invalid HTTP_HOST header: 'localhost:8001'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8001'. You may need to add 'localhost' to ALLOWED_HOSTS.
[14/Sep/2025 11:03:06] "GET / HTTP/1.1" 400 70346
Invalid HTTP_HOST header: 'localhost:8001'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "E:\Local Projects\Django web host\myvenv\Lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8001'. You may need to add 'localhost' to ALLOWED_HOSTS.
[14/Sep/2025 11:03:06] "GET /favicon.ico HTTP/1.1" 400 71009
